
@rootApi=http://localhost:8000/
@userApi={{rootApi}}api/v1/user
###server testing
@burrowApi={{rootApi}}api/v1/burrow
@reviewApi={{rootApi}}api/v1/review
GET {{rootApi}}


####GET USER
GET {{userApi}}

####create USER
POST {{userApi}}
Content-Type: application/json

{
    "role":"admin",
    "fName":"Sumit",
    "lName": "Mahat",
    "phone" :"123456",
    "email" : "mahatsut3@gmail.com",
    "password" :"thisispass",
    "address":"sydney"
}


#=========burrow api
####post book

POST {{burrowApi}}
Content-Type: application/json

{
    "bookId":"asdfdsaf",
    "bookName":"sumit",
    "thumbnail":"",
    "userId":"alskdjfdsakfa",
    "UserName":"Sumit Mahat",
    "dueDate":"",
    "isReturned":"",
    "returnDate":""


}


####put 
PUT {{burrowApi}}
Content-Type: application/json

{
    "_id":"64a9109ffaaf8f756e26e4ac",
    "bookId":"64a90b95faaf8f756e26e473"
}


#==================review api
#####GET

GET {{reviewApi}}
Content-Type: application/json

{
    "bookId":"64a90b95faaf8f756e26e473"
}